apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: default
  annotations:
    notifications.argoproj.io/subscribe.on-rollbacks.rollback: ""
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      shareProcessNamespace: true
      containers:
        - name: my-app
          image: nginx:latest
          ports:
            - containerPort: 80