apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      shareProcessNamespace: true
      containers:
        - name: my-app
          image: nginx:latest
          ports:
            - containerPort: 80

        - name: autoinstrumenter
          image: grafana/beyla:latest
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 0
            privileged: true
            capabilities:
              add: ["SYS_ADMIN", "SYS_PTRACE"]
          env:
            - name: BEYLA_SERVICE_NAME
              value: "dotNet-app"
            - name: BEYLA_METRICS_ENABLED
              value: "true"
            - name: BEYLA_OPEN_PORT
              value: "8080"
            - name: OTEL_EXPORTER_OTLP_METRICS_ENDPOINT
              value: "http://opentelemetrycollector.default.svc.cluster.local:4318"
            - name: BEYLA_LOG_LEVEL
              value: "DEBUG"
            - name: OTEL_METRICS_EXPORTER
              value: "otlp"
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: "service.name=dotNet-app"
            - name: BEYLA_BPF_TRACK_REQUEST_HEADERS
              value: "true"
